version: '3'

services:
  database:
    image: "mysql:5.7-debian"
    env_file:
      - .env.local
    command: "--default-authentication-plugin=mysql_native_password"
    volumes:
      - "/var/db:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE:      ${MYSQL_DATABASE}
      MYSQL_USER:          ${MYSQL_USER}
      MYSQL_PASSWORD:      ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
